# Generated by Django 5.2.7 on 2025-10-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
