# Generated by Django 5.2.7 on 2025-10-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_rename_is_acitve_turf_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='price_per_hour',
            new_name='day_price_per_hour',
        ),
        migrations.RemoveField(
            model_name='turfimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='turf',
            name='day_start_time',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AddField(
            model_name='turf',
            name='night_price_per_hour',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turf',
            name='night_start_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='turf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
