# Generated by Django 5.2.7 on 2025-10-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_rename_price_per_hour_turf_day_price_per_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
